// File generated by FlutterFire CLI (manual equivalent).
// Do not modify by hand — re-run `flutterfire configure` to regenerate.
//
// Project: donoraplus-b2d5e
// Platforms: Android, iOS

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for each platform.
class DefaultFirebaseOptions {
  const DefaultFirebaseOptions._();

  /// Returns the correct [FirebaseOptions] for the current platform.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web — '
        'run `flutterfire configure` to generate web options.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported on '
          '${defaultTargetPlatform.name}',
        );
    }
  }

  /// Android config — derived from android/app/google-services.json.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUPHWN5i7IRlT4XaoMeipQ0gS55lAbra8',
    appId: '1:24737668883:android:d0cd36f0d033d074f244e6',
    messagingSenderId: '24737668883',
    projectId: 'donoraplus-b2d5e',
    storageBucket: 'donoraplus-b2d5e.firebasestorage.app',
  );

  /// iOS config — derived from ios/Runner/GoogleService-Info.plist.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCABnJuotoW811HIRySRb4MMMMFTDZp5Vk',
    appId: '1:24737668883:ios:23a0b1ccb1962c9ff244e6',
    messagingSenderId: '24737668883',
    projectId: 'donoraplus-b2d5e',
    storageBucket: 'donoraplus-b2d5e.firebasestorage.app',
    iosBundleId: 'com.app.donora',
  );
}
